version: '3.8'
services:
  miniflux:
    image: miniflux/miniflux:2.0.34
    ports:
    - 8080:8080
    environment:
      DATABASE_URL: postgres://miniflux:secret@postgres/miniflux?sslmode=disable
      RUN_MIGRATIONS: 1
      CREATE_ADMIN: 1
      ADMIN_USERNAME: johndoe
      ADMIN_PASSWORD: password
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: miniflux
      POSTGRES_USER: miniflux
      POSTGRES_PASSWORD: secret
    volumes:
      - ./volumes/postgres/:/var/lib/postgresql/
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      start_period: 30s
